### ISSUE TITLE
Checklist: General checks

### ISSUE THREAD

**Issue by professorf** [professorf/ArcadeSimplex#21]
- [x] **Repository**: Is the source code for this software available at the repository url?

- [x] **License**: Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license?

- [x] **Contribution and authorship**: Has the submitting author made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

**Comment by professorf** [comment]
**Repository**: https://github.com/professorf/ArcadeSimplex
**License**: GPLv3
**Contribution & authorship**: Nick V. Flor is the sole author
