### ISSUE TITLE
Checklist: Functionality

### ISSUE THREAD

**Issue by professorf** [professorf/ArcadeSimplex#22]
- [ ] **Installation**: Does installation proceed as outlined in the documentation?

- [ ] **Functionality**: Have the functional claims of the software been confirmed?

- [ ] **Performance**: If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)
